M48
; DRILL file {KiCad 7.0.8} date Wed Feb 21 14:11:06 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-21T14:11:06-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X122.116Y-71.85
X122.116Y-129.85
X177.116Y-71.85
X177.116Y-129.85
T0
M30
