M48
; DRILL file {KiCad 7.0.8} date Fri May 10 00:52:23 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-10T00:52:23-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X129.838Y-61.84
X129.838Y-118.84
X171.838Y-61.84
X171.838Y-118.84
T0
M30
