M48
; DRILL file {KiCad 7.0.8} date Fri May 10 10:59:22 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-10T10:59:22-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X120.091Y-62.482
X120.091Y-119.482
X177.091Y-62.482
X177.091Y-119.482
T0
M30
