M48
; DRILL file {KiCad 7.0.8} date Tue May  7 22:53:21 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-07T22:53:21-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X131.554Y-53.918
X131.554Y-110.918
X173.554Y-53.918
X173.554Y-110.918
T0
M30
